FROM adoptopenjdk/openjdk11:alpine-slim

COPY build/libs/trip-manager*.jar ./trip-manager.jar

EXPOSE 8080

ENV MONGODB_NAME=trip-manager
ENV MONGODB_HOST=localhost
ENV MONGODB_PORT=27017
ENV MONGODB_USER=mongo
ENV MONGODB_PASSWORD=mongo

ENV REDIS_HOST=localhost
ENV REDIS_PORT=6379
ENV REDIS_PASSWORD=""

ENV BASE_URL=dev.rubyride.co

ENTRYPOINT java -DMONGODB_NAME=$MONGODB_NAME -DMONGODB_HOST=$MONGODB_HOST -DMONGOB_PORT=$MONGODB_PORT -DMONGODB_USER=$MONGODB_USER -DMONGODB_PASSWORD=$MONGODB_PASSWORD -DREDIS_HOST=$REDIS_HOST -DREDIS_PORT=$REDIS_PORT -DREDIS_PASSWORD=$REDIS_PASSWORD -DBASE_URL=$BASE_URL -jar trip-manager.jar
